version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_WITH_SERVER=1
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deno-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/public:/app/public
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge